name: Build PYZ for ARMv7

permissions:
  contents: write
  issues: read

on:
  release:
    types: [published]

jobs:
  build-armv7-pyz:
    runs-on: ubuntu-latest
    name: Build PYZ (armv7)

    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build inside ARMv7 Docker (shiv)
        uses: addnab/docker-run-action@v3
        with:
          image: arm32v7/python:3.11
          options: --platform linux/arm/v7
          run: |
            apt-get update && apt-get install -y gcc libffi-dev libssl-dev
            pip install -r requirements.txt
            pip install shiv
            shiv . -o mmrelay_armv7_${{ steps.get_version.outputs.VERSION }}.pyz -c main --compressed

      - name: Upload PYZ to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mmrelay_armv7_${{ steps.get_version.outputs.VERSION }}.pyz
          asset_name: mmrelay_armv7_${{ steps.get_version.outputs.VERSION }}.pyz
          tag: ${{ github.ref }}
          overwrite: true
