name: Build Windows Executable

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Get version number
        id: get_version
        run: echo "::set-output name=version::${GITHUB_REF##*/}"

      - name: Build executable
        run: pyinstaller --name=mmrelay_${{ steps.get_version.outputs.version }}.exe --onefile --console main.py

      - name: Build installer
        uses: nadeemjazmawe/inno-setup-action-cli@v6.0.5
        with:
          filepath: "/DAppVersion=${{ github.ref_name }} ./mmrelay.iss"

      - name: Rename installer
        run: ren MMRelay_setup.exe MMRelay_setup_${{ steps.get_version.outputs.version }}.exe

      - name: Upload setup.exe to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: MMRelay_setup_${{ steps.get_version.outputs.version }}.exe
          asset_name: MMRelay_setup_${{ steps.get_version.outputs.version }}.exe
          tag: ${{ github.ref }}
          overwrite: true
