name: Post-Release Version Bump (PR)

on:
  release:
    types: [published]

# Set permissions at workflow level
permissions: {}

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      # Limit permissions to only what's needed
      contents: write # For checking out code and pushing changes
      pull-requests: write # For creating the PR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Extract current version
        id: current_version
        run: |
          CURRENT_VERSION=$(grep "version =" setup.cfg | sed 's/.*= //')
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "Current version: $CURRENT_VERSION"

      - name: Calculate next version
        id: next_version
        run: |
          # Split version into parts
          IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"

          # Increment patch version
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=$((${VERSION_PARTS[2]} + 1))

          NEXT_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV
          echo "Next version will be: $NEXT_VERSION"

      - name: Create branch for version bump
        run: |
          git checkout -b bump-version-to-$NEXT_VERSION

      - name: Update version in setup.cfg
        run: |
          sed -i "s/version = $CURRENT_VERSION/version = $NEXT_VERSION/" setup.cfg
          echo "Updated setup.cfg with new version: $NEXT_VERSION"

      - name: Commit changes
        run: |
          git add setup.cfg
          git commit -m "chore: Bump version to $NEXT_VERSION [skip ci]"
          git push origin bump-version-to-$NEXT_VERSION

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Bump version to ${{ env.NEXT_VERSION }}"
          title: "Bump version to ${{ env.NEXT_VERSION }}"
          body: |
            Automated version bump after release of ${{ env.CURRENT_VERSION }}.

            This PR updates the version in setup.cfg to prepare for the next development cycle.
          branch: bump-version-to-${{ env.NEXT_VERSION }}
          base: main
          labels: automated,version-bump
