name: Upload Python Package to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Verify package version
        run: |
          # Print the version that will be used
          echo "Checking package version..."
          VERSION=$(python -c "import sys; sys.path.insert(0, 'src'); import mmrelay; print(mmrelay.__version__)")
          echo "Package will be built with version: $VERSION"
          # Verify it matches setup.cfg
          SETUP_VERSION=$(grep "version =" setup.cfg | sed 's/.*= //')
          echo "Version in setup.cfg: $SETUP_VERSION"
          if [ "$VERSION" != "$SETUP_VERSION" ]; then
            echo "WARNING: Version mismatch between package ($VERSION) and setup.cfg ($SETUP_VERSION)"
            exit 1
          fi
          echo "Version check passed: $VERSION"

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
