name: Build and Publish Shiv Archive

permissions:
  contents: write
  issues: read

on:
  release:
    types: [published]

jobs:
  build-shiv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for setuptools_scm to determine version from git tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install shiv setuptools_scm

      - name: Build Shiv archive
        run: |
          # Create a Shiv archive with the git tag as the version
          shiv -c mmrelay -o mmrelay_${{ github.ref_name }}.pyz --compressed -p "/usr/bin/env python3" .

      - name: Upload Shiv archive to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mmrelay_${{ github.ref_name }}.pyz
          asset_name: mmrelay_${{ github.ref_name }}.pyz
          tag: ${{ github.ref }}
          overwrite: true
